services:
  capstone:
    container_name: capstone
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www  # Mount the local Laravel app to the container
    ports:
      - "9000:9000"  # Expose PHP-FPM on port 9000
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - mysql
      - nginx
    networks:
      - ${PROJECT_NAME}-network
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www  # Mount the app for Nginx as well
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Use your custom Nginx config
    networks:
      - ${PROJECT_NAME}-network
  mysql:
    container_name: mysql
    env_file:
      - path: .env
        required: true
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - vmysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - ${PROJECT_NAME}-network
    healthcheck:
      test: [ CMD, mysqladmin, ping, -h, localhost ]
      timeout: 45s
      interval: 10s
      retries: 10

networks:
  capstone-network:
    name: ${PROJECT_NAME}-network
    driver: bridge
volumes:
  vmysql:
    driver: local
  vredis:
    driver: local